# Generated by Django 2.2.14 on 2020-07-18 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='blogs',
            new_name='blog',
        ),
    ]
